### ISSUE TITLE
Outdated repo...

### ISSUE THREAD

**Issue by repsorp** [binance/desktop#12]
https://github.com/binance/desktop/releases is outdated
most recent binance desktop app is 1.23.0

**Comment by darthvinyll** [comment]
Hear, hear - no build in updater, so no clue where to get the .deb from. Please post a link to the active repo, if available.

**Comment by repsorp** [comment]
Download links are available here:
https://www.binance.com/en/download

Direct links for latest version (version number never mentionned unfortunately...):
macOS
https://ftp.binance.com/electron-desktop/mac/production/binance.dmg
Windows
https://ftp.binance.com/electron-desktop/windows/production/binance-setup.exe
Linux deb
https://ftp.binance.com/electron-desktop/linux/production/binance-amd64-Linux.deb
Linux rpm
https://ftp.binance.com/electron-desktop/linux/production/binance-x86_64-linux.rpm

**Comment by darthvinyll** [comment]
Had me excited there for a sec, but this is clearly not the case for the .deb link - access very much denied:

![2021-09-12_11-24](https://user-images.githubusercontent.com/52528806/132984080-e555203a-44a6-4253-949e-58777235b6f5.png)

**Comment by repsorp** [comment]
Access to ftp must be allowed only from Binance website I guess
[Same link ](https://ftp.binance.com/electron-desktop/linux/production/binance-amd64-Linux.deb) to access .deb here:
https://www.binance.com/en/download
![a](https://user-images.githubusercontent.com/6297032/132984326-5956aa5b-42da-4023-aa47-974d70ab29cf.png)

**Comment by darthvinyll** [comment]
Confirmed to be working (Ubuntu 20.10), thanks!

![2021-09-12_14-06](https://user-images.githubusercontent.com/52528806/132988717-7c4f453b-4a4d-4931-b45c-347abbf8ff3e.png)
