### ISSUE TITLE
New release needed on GitHub

### ISSUE THREAD

**Issue by gittigger** [binance/desktop#14]
Just installed the debian package from here (latest available) and it installs but says there is a later release available( Version: 1.23.1). This then redirects to the website where the only available download is an rpm package. Can you please update the github release page with all the latest downloads?

**Comment by 0wx** [comment]
Github update are pretty late. Just go to https://www.binance.me/en/download and select the latest version.

**Comment by gittigger** [comment]
That was my point. Going to https://www.binance.me/en/download only provided the rpm. Today I see that a deb is now available, when it wasn't before. Closing this as a result, thanks
